export const KEYBOARD_MAP_SPECIAL = {
    '@': ['VK_AT'],
    ',': ['VK_COMMA'],
    '+': ['VK_PLUS'],
    '-': ['VK_MINUS'],
    '*': ['VK_MULTIPLY'],
    '/': ['VK_SLASH'],
    '\\': ['VK_BACK_SLASH'],
    '.': ['VK_PERIOD'],
    ' ': ['VK_SPACE'],
    '€': ['VK_EURO_SIGN'],
    '$': ['VK_DOLLAR'],
    '!': ['VK_EXCLAMATION_MARK'],
    '(': ['VK_LEFT_PARENTHESIS'],
    ')': ['VK_RIGHT_PARENTHESIS'],
    '_': ['VK_UNDERSCORE'],
    '#': ['VK_NUMBER_SIGN'],
    ';': ['VK_SEMICOLON'],
    ':': ['VK_COLON'],
    '=': ['VK_EQUALS'],
    '^': ['VK_CIRCUMFLEX'],
    'CapsLock': ['VK_CAPS_LOCK'],
    'Shift': ['VK_SHIFT'],
    'Backspace': ['VK_BACK_SPACE'],
    'Delete': ['VK_DELETE'],
    'Escape': ['VK_ESCAPE'],
    'Enter': ['VK_ENTER'],
    'ClearAll': ['VK_CONTROL', 'VK_A', 'VK_BACK_SPACE'],
    'A': ['VK_SHIFT', 'VK_A'],
    'B': ['VK_SHIFT', 'VK_B'],
    'C': ['VK_SHIFT', 'VK_C'],
    'D': ['VK_SHIFT', 'VK_D'],
    'E': ['VK_SHIFT', 'VK_E'],
    'F': ['VK_SHIFT', 'VK_F'],
    'G': ['VK_SHIFT', 'VK_G'],
    'H': ['VK_SHIFT', 'VK_H'],
    'I': ['VK_SHIFT', 'VK_I'],
    'J': ['VK_SHIFT', 'VK_J'],
    'K': ['VK_SHIFT', 'VK_K'],
    'L': ['VK_SHIFT', 'VK_L'],
    'M': ['VK_SHIFT', 'VK_M'],
    'N': ['VK_SHIFT', 'VK_N'],
    'O': ['VK_SHIFT', 'VK_O'],
    'P': ['VK_SHIFT', 'VK_P'],
    'Q': ['VK_SHIFT', 'VK_Q'],
    'R': ['VK_SHIFT', 'VK_R'],
    'S': ['VK_SHIFT', 'VK_S'],
    'T': ['VK_SHIFT', 'VK_T'],
    'U': ['VK_SHIFT', 'VK_U'],
    'V': ['VK_SHIFT', 'VK_V'],
    'W': ['VK_SHIFT', 'VK_W'],
    'X': ['VK_SHIFT', 'VK_X'],
    'Y': ['VK_SHIFT', 'VK_Y'],
    'Z': ['VK_SHIFT', 'VK_Z'],
    'a': ['VK_A'],
    'b': ['VK_B'],
    'c': ['VK_C'],
    'd': ['VK_D'],
    'e': ['VK_E'],
    'f': ['VK_F'],
    'g': ['VK_G'],
    'h': ['VK_H'],
    'i': ['VK_I'],
    'j': ['VK_J'],
    'k': ['VK_K'],
    'l': ['VK_L'],
    'm': ['VK_M'],
    'n': ['VK_N'],
    'o': ['VK_O'],
    'p': ['VK_P'],
    'q': ['VK_Q'],
    'r': ['VK_R'],
    's': ['VK_S'],
    't': ['VK_T'],
    'u': ['VK_U'],
    'v': ['VK_V'],
    'w': ['VK_W'],
    'x': ['VK_X'],
    'y': ['VK_Y'],
    'z': ['VK_Z'],
    '0': ['VK_0'],
    '1': ['VK_1'],
    '2': ['VK_2'],
    '3': ['VK_3'],
    '4': ['VK_4'],
    '5': ['VK_5'],
    '6': ['VK_6'],
    '7': ['VK_7'],
    '8': ['VK_8'],
    '9': ['VK_9']
}